import AppleLogo from './assets/Apple-Logo.png'
import Wipro from './assets/WIT.png'
import Cts from './assets/CTSH_BIG.png'
import AmazonLogo from './assets/AMZN_BIG.png'
import Google from './assets/GOOG.png'
import InfyLogo from './assets/INFY_BIG.png'
import Tcs from './assets/TCS.png'
import metaLogo from './assets/META_BIG.png'

// export const CompaniesList = [
//   {
//     "companyName": "Apple IN",
//     "companyId": "AIN001",
//     "TopCompany": true,
//     "logo": AppleLogo,
//     "slogan": "Think Different",
//     "ratings": 3.5,
//     "reviewNo": 533
//   },
//   {
//     "companyName": "Cognizant Technologies",
//     "companyId": "CTS001",
//     "TopCompany": true,
//     "logo": Cts,
//     "slogan": "Leading ITeS company with global presence",
//     "ratings": 3.9,
//     "reviewNo": 854
//   },
//   {
//     "companyName": "InfoSys Technologies",
//     "companyId": "IST001",
//     "TopCompany": true,
//     "logo": InfyLogo,
//     "slogan": "Navigate your next",
//     "ratings": 3.6,
//     "reviewNo": 1854
//   },
//   {
//     "companyName": "Wipro Limited",
//     "companyId": "WIB001",
//     "TopCompany": true,
//     "logo": Wipro,
//     "slogan": "Grow with us. Be bold.",
//     "ratings": 3.8,
//     "reviewNo": 968
//   },
//   {
//     "companyName": "META",
//     "companyId": "MET001",
//     "TopCompany": true,
//     "logo": metaLogo,
//     "slogan": "Bring the world closer together",
//     "ratings": 4.2,
//     "reviewNo": 669
//   },
//   {
//     "companyName": "Google",
//     "companyId": "GGL001",
//     "TopCompany": true,
//     "logo": Google,
//     "slogan": "Change lifes",
//     "ratings": 4.4,
//     "reviewNo": 869
//   },
//   {
//     "companyName": "Tata Consultancy Services",
//     "companyId": "TCS001",
//     "TopCompany": true,
//     "logo": Tcs,
//     "slogan": "Building on belief",
//     "ratings": 3.9,
//     "reviewNo": 259
//   },
//   {
//     "companyName": "Amazon",
//     "companyId": "AMZ001",
//     "TopCompany": true,
//     "logo": AmazonLogo,
//     "slogan": "Deliver happiness",
//     "ratings": 4.2,
//     "reviewNo": 759
//   },
//   {
//     "companyName": "Tech Solutions Inc.",
//     "companyId": "TSI001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 3.5,
//     "reviewNo": 533
//   },
//   {
//     "companyName": "Innovate Software Corp.",
//     "companyId": "ISC001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 4.5,
//     "reviewNo": 523
//   },
//   {
//     "companyName": "Global Connect Media",
//     "companyId": "GCM001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 2.5,
//     "reviewNo": 400
//   },
//   {
//     "companyName": "Apex Consulting Group",
//     "companyId": "ACG001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 3.0,
//     "reviewNo": 253
//   },
//   {
//     "companyName": "Ed-Tech Pioneers",
//     "companyId": "ETP001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 3.5,
//     "reviewNo": 158
//   },
//   {
//     "companyName": "Digital Forge Systems",
//     "companyId": "DFS001",
//     "TopCompany": true,
//     "logo": "",
//     "slogan": "",
//     "ratings": 3.7,
//     "reviewNo": 512
//   },
//   {
//     "companyName": "Marketing Zenith Agency",
//     "companyId": "MZA001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 4.1,
//     "reviewNo": 248
//   },
//   {
//     "companyName": "BioGen Pharma Labs",
//     "companyId": "BPL001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 2.9,
//     "reviewNo": 487
//   },
//   {
//     "companyName": "ConnectPro Telecom",
//     "companyId": "CPT001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 2.9,
//     "reviewNo": 417
//   },
//   {
//     "companyName": "Future Mobility Autos",
//     "companyId": "FMA001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 4.2,
//     "reviewNo": 687
//   },
//   {
//     "companyName": "AI Insights Hub",
//     "companyId": "AIH001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 3.8,
//     "reviewNo": 357
//   },
//   {
//     "companyName": "Construct Mega Projects",
//     "companyId": "CMP001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 2.8,
//     "reviewNo": 754
//   },
//   {
//     "companyName": "Talent Bridge Solutions",
//     "companyId": "TBS001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 4.3,
//     "reviewNo": 485
//   },
//   {
//     "companyName": "Nexus Web Labs",
//     "companyId": "NWL001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 3.5,
//     "reviewNo": 175
//   },
//   {
//     "companyName": "Logistics Xpress",
//     "companyId": "LX001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 4.6,
//     "reviewNo": 1047
//   },
//   {
//     "companyName": "AeroDynamics R&D",
//     "companyId": "ADRD001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 3.7,
//     "reviewNo": 684
//   },
//   {
//     "companyName": "MedCare Multi-Specialty Hospital",
//     "companyId": "MMSH001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 2.75,
//     "reviewNo": 514
//   },
//   {
//     "companyName": "Consumer Goods Titans (CGT)",
//     "companyId": "CGT001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 4.7,
//     "reviewNo": 718
//   },
//   {
//     "companyName": "Green Energy Solutions",
//     "companyId": "PPMT001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 2.5,
//     "reviewNo": 115
//   },
//   {
//     "companyName": "SecureNet Consulting",
//     "companyId": "SNC001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 3.7,
//     "reviewNo": 533
//   },
//   {
//     "companyName": "MarketiQ Labs",
//     "companyId": "DME001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 3.7,
//     "reviewNo": 486
//   },
//   {
//     "companyName": "BuildSphere Tech",
//     "companyId": "BST001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 4.2,
//     "reviewNo": 533
//   },
//   {
//     "companyName": "HelpDesk Pro",
//     "companyId": "HDP001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 2.5,
//     "reviewNo": 356
//   },
//   {
//     "companyName": "ProManage Global",
//     "companyId": "PMG001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 4.05,
//     "reviewNo": 485
//   },
//   {
//     "companyName": "TestFlow Systems",
//     "companyId": "TFS001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 3.9,
//     "reviewNo": 286
//   },
//   {
//     "companyName": "BrightBooks Finance",
//     "companyId": "BBF001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 4.2,
//     "reviewNo": 659
//   },
//   {
//     "companyName": "GrowMore Pvt Ltd",
//     "companyId": "GPL001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 3.9,
//     "reviewNo": 278
//   },
//   {
//     "companyName": "TrendHive Digital",
//     "companyId": "THD001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 4.3,
//     "reviewNo": 533
//   },
//   {
//     "companyName": "NetSecure IT",
//     "companyId": "NSI001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 4.2,
//     "reviewNo": 586
//   },
//   {
//     "companyName": "NeuroMind AI",
//     "companyId": "NMAI001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 4.7,
//     "reviewNo": 685
//   },
//   {
//     "companyName": "Metrics Fusion Ltd.",
//     "companyId": "MFL001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 4.5,
//     "reviewNo": 289
//   },
//   {
//     "companyName": "Predictive Innovations",
//     "companyId": "PI001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 2.5,
//     "reviewNo": 485
//   },
//   {
//     "companyName": "Nexus Growth Platform",
//     "companyId": "NGP001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 4.4,
//     "reviewNo": 786
//   },
//   {
//     "companyName": "Digital Reach Agency",
//     "companyId": "DIA001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 2.7,
//     "reviewNo": 685
//   },
//   {
//     "companyName": "HealthData Insights",
//     "companyId": "HDI001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 4.5,
//     "reviewNo": 259
//   },
//   {
//     "companyName": "Growth Accelerate Co.",
//     "companyId": "GAC001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 2.7,
//     "reviewNo": 354
//   },
//   {
//     "companyName": "Enterprise Flow Solutions",
//     "companyId": "EFS001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 3.65,
//     "reviewNo": 258
//   },
//   {
//     "companyName": "Insightful Media Group",
//     "companyId": "IMG001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 3.5,
//     "reviewNo": 485
//   },
//   {
//     "companyName": "Customer Lifecycle Hub",
//     "companyId": "CLH001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 1.5,
//     "reviewNo": 198
//   },
//   {
//     "companyName": "Regional Connect Tech",
//     "companyId": "RCT001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 2.95,
//     "reviewNo": 85
//   },
//   {
//     "companyName": "Nexus Scale",
//     "companyId": "NXS001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 4.25,
//     "reviewNo": 653
//   },
//   {
//     "companyName": "EvoUI Solutions",
//     "companyId": "EUIS001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 1.75,
//     "reviewNo": 624
//   },
//   {
//     "companyName": "Global DataFlow",
//     "companyId": "GDF001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 1.5,
//     "reviewNo": 495
//   },
//   {
//     "companyName": "Mobile Innovate Co.",
//     "companyId": "MIC001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 3.85,
//     "reviewNo": 25
//   },
//   {
//     "companyName": "Cloud Reliability Hub",
//     "companyId": "CRH001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 4.15,
//     "reviewNo": 568
//   },
//   {
//     "companyName": "Synergy Labs",
//     "companyId": "SPD001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 3.75,
//     "reviewNo": 698
//   },
//   {
//     "companyName": "Pixel Perfect Studio",
//     "companyId": "PPS001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 4.15,
//     "reviewNo": 258
//   },
//   {
//     "companyName": "User Insights Co.",
//     "companyId": "UIC001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 2.25,
//     "reviewNo": 1865
//   },
//   {
//     "companyName": "Velocity Mobile App",
//     "companyId": "VMA001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 2.25,
//     "reviewNo": 188
//   },
//   {
//     "companyName": "Retail Stream Digital",
//     "companyId": "RSD001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 2.5,
//     "reviewNo": 785
//   },
//   {
//     "companyName": "PixelCoders Tech",
//     "companyId": "PCT001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 4.3,
//     "reviewNo": 533
//   },
//   {
//     "companyName": "SkyBase Solutions",
//     "companyId": "SBS001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 4.5,
//     "reviewNo": 258
//   },
//   {
//     "companyName": "DesignSphere Studio",
//     "companyId": "DSS001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 1.75,
//     "reviewNo": 156
//   },
//   {
//     "companyName": "CodeMatrix Pvt Ltd",
//     "companyId": "CMPL001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 3.5,
//     "reviewNo": 533
//   },
//   {
//     "companyName": "InsightTech Analytics",
//     "companyId": "ITA001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 2.25,
//     "reviewNo": 156
//   },
//   {
//     "companyName": "AppCrafters Lab",
//     "companyId": "ACL001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 4.0,
//     "reviewNo": 35
//   },
//   {
//     "companyName": "CreativeVista Agency",
//     "companyId": "CVA001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 5.0,
//     "reviewNo": 1586
//   },
//   {
//     "companyName": "TalentHive HR",
//     "companyId": "THHR001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 4.5,
//     "reviewNo": 256
//   },
//   {
//     "companyName": "CloudNova Systems",
//     "companyId": "CNS001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 2.5,
//     "reviewNo": 5164
//   },
//   {
//     "companyName": "Visionary Corp",
//     "companyId": "VCO001",
//     "TopCompany": false,
//     "logo": "",
//     "slogan": "",
//     "ratings": 2.5,
//     "reviewNo": 158
//   }
// ]
export const CompaniesList = [
{
        id: "EMP001",
        companyId: "AIN001",
        companyName: "Apple IN",
        companyMoto: "Think Different",
        contactPerson: "Sudhakar K",
        contactNumber: "+91 9876543210",
        companyMail: "sudhakar@apple.in",
        website: "https://apple.com/in",
        companySize: "10000+",
        address1: "Embassy GolfLinks",
        address2: "Challaghatta, Bangalore",
        about: "Leading technology company specialized in consumer electronics.",
        companyLogo: AppleLogo,
        role: "employer",
        jobPosted: ["JOB101", "JOB102"],
        messages: [],
        joinDate: "01/02/2022",
        ratings: 4.8,
        reviewNo: 15420,
        slogan: "Innovating for a better world"
    },
    {
        id: "EMP002",
        companyId: "AIN001", // Duplicate Company (HR 2 for Apple)
        companyName: "Apple IN",
        companyMoto: "Think Different",
        contactPerson: "Meera Krishnan",
        contactNumber: "+91 9876543211",
        companyMail: "meera.hr@apple.in",
        website: "https://apple.com/in",
        companySize: "10000+",
        address1: "Embassy GolfLinks",
        address2: "Challaghatta, Bangalore",
        about: "Leading technology company specialized in consumer electronics.",
        companyLogo: AppleLogo,
        role: "employer",
        jobPosted: ["JOB103"],
        messages: [],
        joinDate: "15/03/2023",
        ratings: 4.8,
        reviewNo: 15420,
        slogan: "Innovating for a better world"
    },
    {
        id: "EMP003",
        companyId: "IST001",
        companyName: "Infotech",
        companyMoto: "Navigate your next",
        contactPerson: "Rajesh Kumar",
        contactNumber: "+91 9444556677",
        companyMail: "hr@infotech.com",
        website: "https://infotech.io",
        companySize: "5000-10000",
        address1: "Sholinganallur",
        address2: "OMR, Chennai",
        about: "Global leader in next-generation digital services and consulting.",
        companyLogo: InfyLogo,
        role: "employer",
        jobPosted: ["JOB201", "JOB202"],
        messages: [],
        joinDate: "10/05/2021",
        ratings: 3.6,
        reviewNo: 1854,
        slogan: "Building the future together"
    },
    {
        id: "EMP004",
        companyId: "IST001", // Duplicate Company (HR 2 for Infotech)
        companyName: "Infotech",
        companyMoto: "Navigate your next",
        contactPerson: "Priya Dharshini",
        contactNumber: "+91 9444556678",
        companyMail: "priya.ta@infotech.com",
        website: "https://infotech.io",
        companySize: "5000-10000",
        address1: "Sholinganallur",
        address2: "OMR, Chennai",
        about: "Global leader in next-generation digital services and consulting.",
        companyLogo: InfyLogo,
        role: "employer",
        jobPosted: [],
        messages: [],
        joinDate: "20/08/2022",
        ratings: 3.6,
        reviewNo: 1854,
        slogan: "Building the future together"
    },
    {
        id: "EMP005",
        companyId: "GGL001",
        companyName: "Google Cloud",
        companyMoto: "Organizing World's Information",
        contactPerson: "Arun V",
        contactNumber: "+91 9000111222",
        companyMail: "arun.hr@google.com",
        website: "https://cloud.google.com",
        companySize: "10000+",
        address1: "RMZ Infinity",
        address2: "Old Madras Road, Bangalore",
        about: "Cloud computing services that help businesses scale and grow.",
        companyLogo: Google,
        role: "employer",
        jobPosted: ["JOB301", "JOB302"],
        messages: [],
        joinDate: "12/01/2020",
        ratings: 4.9,
        reviewNo: 22100,
        slogan: "Cloud with confidence"
    },
    {
        id: "EMP006",
        companyId: "GGL001", // Duplicate (HR 2 for Google)
        companyName: "Google Cloud",
        companyMoto: "Organizing World's Information",
        contactPerson: "Sanjay Raj",
        contactNumber: "+91 9000111223",
        companyMail: "sanjay.talent@google.com",
        website: "https://cloud.google.com",
        companySize: "10000+",
        address1: "RMZ Infinity",
        address2: "Old Madras Road, Bangalore",
        about: "Cloud computing services that help businesses scale and grow.",
        companyLogo: Google,
        role: "employer",
        jobPosted: ["JOB303"],
        messages: [],
        joinDate: "05/11/2021",
        ratings: 4.9,
        reviewNo: 22100,
        slogan: "Cloud with confidence"
    },
    {
        id: "EMP007",
        companyId: "CTS001",
        companyName: "Cognizant",
        companyMoto: "The Operating System for Business",
        contactPerson: "Karthiga R",
        contactNumber: "+91 9112233445",
        companyMail: "karthiga@zohocorp.com",
        website: "https://zoho.com",
        companySize: "5000-10000",
        address1: "Estancia IT Park",
        address2: "Guduvanchery, Chennai",
        about: "Indian multinational technology company that makes business tools.",
        companyLogo: Cts,
        role: "employer",
        jobPosted: ["JOB401"],
        messages: [],
        joinDate: "17/09/2019",
        ratings: 4.5,
        reviewNo: 9800,
        slogan: "Software is our craft"
    },
    {
        id: "EMP008",
        companyId: "CTS001", // Duplicate (HR 2 for Zoho)
        companyName: "Cognizant",
        companyMoto: "The Operating System for Business",
        contactPerson: "Vimal Kumar",
        contactNumber: "+91 9112233446",
        companyMail: "vimal.hr@zohocorp.com",
        website: "https://zoho.com",
        companySize: "5000-10000",
        address1: "Estancia IT Park",
        address2: "Guduvanchery, Chennai",
        about: "Indian multinational technology company that makes business tools.",
        companyLogo: Cts,
        role: "employer",
        jobPosted: ["JOB402"],
        messages: [],
        joinDate: "10/01/2023",
        ratings: 4.5,
        reviewNo: 9800,
        slogan: "Software is our craft"
    },
    {
        id: "EMP009",
        companyId: "TCS001",
        companyName: "TCS",
        companyMoto: "Building on Belief",
        contactPerson: "Anjali Sharma",
        contactNumber: "+91 8877665544",
        companyMail: "anjali.s@tcs.com",
        website: "https://tcs.com",
        companySize: "10000+",
        address1: "Siruseri IT Park",
        address2: "Chennai",
        about: "Leader in IT services, consulting and business solutions.",
        companyLogo: Tcs,
        role: "employer",
        jobPosted: ["JOB501", "JOB502", "JOB503"],
        messages: [],
        joinDate: "01/01/2021",
        ratings: 3.8,
        reviewNo: 45000,
        slogan: "Experience certainty"
    },
    {
        id: "EMP010",
        companyId: "TCS001", // Duplicate (HR 2 for TCS)
        companyName: "TCS",
        companyMoto: "Building on Belief",
        contactPerson: "Rohan Das",
        contactNumber: "+91 8877665545",
        companyMail: "rohan.hr@tcs.com",
        website: "https://tcs.com",
        companySize: "10000+",
        address1: "Siruseri IT Park",
        address2: "Chennai",
        about: "Leader in IT services, consulting and business solutions.",
        companyLogo: Tcs,
        role: "employer",
        jobPosted: [],
        messages: [],
        joinDate: "15/06/2023",
        ratings: 3.8,
        reviewNo: 45000,
        slogan: "Experience certainty"
    },
    {
        id: "EMP011",
        companyId: "PIX005",
        companyName: "Pixel Logic",
        companyMoto: "Crafting Digital Experiences",
        contactPerson: "Thomas Antony",
        contactNumber: "+91 7766554433",
        companyMail: "hr@pixellogic.com",
        website: "https://pixellogic.io",
        companySize: "50-100",
        address1: "No 12, OMR Road",
        address2: "Thoraipakkam, Chennai",
        about: "Leading UI/UX agency.",
        companyLogo: "pixel.png",
        role: "employer",
        jobPosted: ["JOB601"],
        messages: [],
        joinDate: "01/02/2022",
        ratings: 4.2,
        reviewNo: 450,
        slogan: "Design that speaks"
    },
    {
        id: "EMP012",
        companyId: "AMZ001",
        companyName: "Amazon Dev Center",
        companyMoto: "Customer Obsession",
        contactPerson: "Naveen Chand",
        contactNumber: "+91 9888112233",
        companyMail: "naveen@amazon.com",
        website: "https://amazon.jobs",
        companySize: "10000+",
        address1: "WTC, Perungudi",
        address2: "Chennai",
        about: "Earth's most customer-centric company.",
        companyLogo: AmazonLogo,
        role: "employer",
        jobPosted: ["JOB701", "JOB702"],
        messages: [],
        joinDate: "20/03/2020",
        ratings: 4.1,
        reviewNo: 32000,
        slogan: "Work Hard, Have Fun, Make History"
    },
    {
        id: "EMP013",
        companyId: "AMZ001", // Duplicate (HR 2 for Amazon)
        companyName: "Amazon Dev Center",
        companyMoto: "Customer Obsession",
        contactPerson: "Lithin",
        contactNumber: "+91 9888112234",
        companyMail: "lithin.hr@amazon.com",
        website: "https://amazon.jobs",
        companySize: "10000+",
        address1: "WTC, Perungudi",
        address2: "Chennai",
        about: "Earth's most customer-centric company.",
        companyLogo: AmazonLogo,
        role: "employer",
        jobPosted: ["JOB703"],
        messages: [],
        joinDate: "10/12/2022",
        ratings: 4.1,
        reviewNo: 32000,
        slogan: "Work Hard, Have Fun, Make History"
    },
    {
        id: "EMP014",
        companyId: "MSF007",
        companyName: "Microsoft India",
        companyMoto: "Empowering every person",
        contactPerson: "Gowtham Sam",
        contactNumber: "+91 9900110022",
        companyMail: "gowtham@microsoft.com",
        website: "https://microsoft.com",
        companySize: "10000+",
        address1: "Gachibowli",
        address2: "Hyderabad",
        about: "Global tech leader in software and cloud.",
        companyLogo: "microsoft.png",
        role: "employer",
        jobPosted: ["JOB801"],
        messages: [],
        joinDate: "25/07/2019",
        ratings: 4.7,
        reviewNo: 28000,
        slogan: "Be what's next"
    },
    {
        id: "EMP015",
        companyId: "FRE009",
        companyName: "Freshworks",
        companyMoto: "Delight Made Easy",
        contactPerson: "Vikram Seth",
        contactNumber: "+91 9123456789",
        companyMail: "careers@freshworks.com",
        website: "https://freshworks.com",
        companySize: "1000-5000",
        address1: "Global Infocity",
        address2: "Perungudi, Chennai",
        about: "SaaS platform for customer engagement.",
        companyLogo: "freshworks.png",
        role: "employer",
        jobPosted: ["JOB901"],
        messages: [],
        joinDate: "15/02/2022",
        ratings: 4.3,
        reviewNo: 3100,
        slogan: "Refreshingly easy software"
    },
    {
        id: "EMP016",
        companyId: "FRE009", // Duplicate (HR 2 for Freshworks)
        companyName: "Freshworks",
        companyMoto: "Delight Made Easy",
        contactPerson: "Sruthi P",
        contactNumber: "+91 9123456780",
        companyMail: "sruthi.ta@freshworks.com",
        website: "https://freshworks.com",
        companySize: "1000-5000",
        address1: "Global Infocity",
        address2: "Perungudi, Chennai",
        about: "SaaS platform for customer engagement.",
        companyLogo: "freshworks.png",
        role: "employer",
        jobPosted: [],
        messages: [],
        joinDate: "10/06/2023",
        ratings: 4.3,
        reviewNo: 3100,
        slogan: "Refreshingly easy software"
    },
    {
        id: "EMP017",
        companyId: "CTS001",
        companyName: "Cognizant",
        companyMoto: "Intuition Engineered",
        contactPerson: "Abirami V",
        contactNumber: "+91 9444001122",
        companyMail: "abi@cognizant.com",
        website: "https://cognizant.com",
        companySize: "10000+",
        address1: "MEPZ",
        address2: "Tambaram, Chennai",
        about: "Leading professional services company.",
        companyLogo: Cts,
        role: "employer",
        jobPosted: ["JOB1001", "JOB1002"],
        messages: [],
        joinDate: "20/11/2021",
        ratings: 3.5,
        reviewNo: 55000,
        slogan: "Keep challenging"
    },
    {
        id: "EMP018",
        companyId: "WIB001",
        companyName: "Wipro",
        companyMoto: "Spirit of Wipro",
        contactPerson: "Suresh Raina",
        contactNumber: "+91 8080808080",
        companyMail: "suresh@wipro.com",
        website: "https://wipro.com",
        companySize: "10000+",
        address1: "Sarjapur Road",
        address2: "Bangalore",
        about: "Information technology, consulting services.",
        companyLogo: Wipro,
        role: "employer",
        jobPosted: ["JOB1101"],
        messages: [],
        joinDate: "01/04/2022",
        ratings: 3.4,
        reviewNo: 48000,
        slogan: "Applying Thought"
    },
    {
        id: "EMP019",
        companyId: "FLI012",
        companyName: "Flipkart",
        companyMoto: "Ab Har Wish Hogi Poori",
        contactPerson: "Dinesh K",
        contactNumber: "+91 7070707070",
        companyMail: "dinesh.hr@flipkart.com",
        website: "https://flipkart.com",
        companySize: "5000-10000",
        address1: "Outer Ring Road",
        address2: "Bangalore",
        about: "India's leading e-commerce marketplace.",
        companyLogo: "flipkart.png",
        role: "employer",
        jobPosted: ["JOB1201", "JOB1202"],
        messages: [],
        joinDate: "15/09/2022",
        ratings: 4.4,
        reviewNo: 12000,
        slogan: "The New Pinch"
    },
    {
        id: "EMP020",
        companyId: "FLI012", // Duplicate (HR 2 for Flipkart)
        companyName: "Flipkart",
        companyMoto: "Ab Har Wish Hogi Poori",
        contactPerson: "Divya M",
        contactNumber: "+91 7070707071",
        companyMail: "divya.hr@flipkart.com",
        website: "https://flipkart.com",
        companySize: "5000-10000",
        address1: "Outer Ring Road",
        address2: "Bangalore",
        about: "India's leading e-commerce marketplace.",
        companyLogo: "flipkart.png",
        role: "employer",
        jobPosted: [],
        messages: [],
        joinDate: "10/01/2024",
        ratings: 4.4,
        reviewNo: 12000,
        slogan: "The New Pinch"
    }
];